version: '3.8'

services:
  omop-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: omop_cdm
      POSTGRES_USER: omopuser
      POSTGRES_PASSWORD: omop
    ports:
      - "5436:5432"
    volumes:
      - omop_data:/var/lib/postgresql/data
      - ../data/omop_data/cms-synthetic-omop/postgres/cms-synthetic-omop.sql:/docker-entrypoint-initdb.d/01-omop.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omopuser -d omop_cdm"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2.00'

volumes:
  omop_data: